### ISSUE TITLE
Pantheon specific config do not show by default

### ISSUE THREAD

**Issue by carl-alberto** [pantheon-systems/pantheon-mu-plugin#14]
Since these [lines](https://github.com/pantheon-systems/pantheon-mu-plugin/blob/a185eeb0b424fe3e347bc064eae4c7af90ad3a6e/pantheon.php#L45-L47) supposedly will help not putting the `define( 'WP_ALLOW_MULTISITE', true );` in the wp-config because this plugin does it automatically

But still it gives this link under the Tools > Network setup

https://dev-example.pantheonsite.io/wp-admin/network.php

![Screen Shot 2023-05-09 at 6 41 54 AM](https://user-images.githubusercontent.com/5098765/236953167-8fae8783-b88d-44da-ba03-98193badfa0e.png)

The correct admin page eg: https://dev-example.pantheonsite.io/wp-admin/tools.php?page=setup_network only appears after adding `define( 'MULTISITE', true );` in the wp-config

![Screen Shot 2023-05-09 at 6 42 14 AM](https://user-images.githubusercontent.com/5098765/236953199-5286b377-e829-455d-9eac-a4104948c94a.png)

**Comment by jazzsequence** [comment]
Fixed via #21
