### ISSUE TITLE
Possibly enforce WP coding standards

### ISSUE THREAD

**Issue by carl-alberto** [pantheon-systems/pantheon-mu-plugin#18]
Would it be neat if we can get the code linted with [WPPHPCS ](https://github.com/WordPress/WordPress-Coding-Standards)

or possibly using existing GH actions in the marketplace like https://github.com/rtCamp/action-phpcs-code-review

or better yet https://packagist.org/packages/pantheon-systems/pantheon-wp-coding-standards

**Comment by jazzsequence** [comment]
We've been using our own [Pantheon WP Coding Standards](https://github.com/pantheon-systems/pantheon-wp-coding-standards) since #25. Closing this.
