### ISSUE TITLE
[CMSP-1033] Preferred method to skip modifying the cache-control

### ISSUE THREAD

**Issue by ecaron** [pantheon-systems/pantheon-mu-plugin#37]
We have some situations where other plugins need to manipulate the Cache-Control header for various reasons. However the [mu plugin makes that difficult](https://github.com/pantheon-systems/pantheon-mu-plugin/blob/be5a6d2721315d51e373da5960f0b2aff1769044/inc/pantheon-page-cache.php#L365
) to debug or adjust.

One way this can be handled is with a heavy-handed `remove_action` call, like this:
```
remove_action( 'send_headers', array( \Pantheon_Cache::instance(), 'cache_add_headers' ) );
```
I was wondering if you'd consider adding, within the `cache_add_headers` method, something like:
```
if ( do_action( 'skip_pantheon_cache_control') ) {
  return;
}
```
And then plugin developers could add something like this in their plugin to circument the cache without reaching into the instance.
```
add_filter( 'skip_pantheon_cache_control', '__return_true' );
```

If your code standards prefer the `remove_action` approach, that's fine. I didn't see prior art of it in other Pantheon plugins, so I figured this is a feature you'd consider introducing.

**Comment by scottbuscemi** [comment]
Thanks Eric. I'm all for actions and filters for our WP plugins.

**Comment by ecaron** [comment]
@scottbuscemi Now that this is associated with CMSP-1033, does that mean someone at Pantheon is already planning on doing this? Or would you accept a PR if I submit one?

**Comment by scottbuscemi** [comment]
@jazzsequence Preference on PR or having us write it?

**Comment by jazzsequence** [comment]
I wrote a PR but happy to have your eyes on it @ecaron if it's along the lines of what you were thinking.

**Comment by westonruter** [comment]
Follow up PR: https://github.com/pantheon-systems/pantheon-mu-plugin/pull/94
