### ISSUE TITLE
Return uncached taxonomy terms in Gutenberg to allow new terms to be added

### ISSUE THREAD

**Issue by cleverington** [pantheon-systems/pantheon-mu-plugin#8]
Was referred to submit a potential issue from [Pantheon's Slack](https://pantheon-community.slack.com/archives/CT8MC5Y0K/p1677084530613509).

## Slack Notes

Issue already patched within the MU-Plugin at around https://github.com/pantheon-systems/WordPress/pull/337/files that does not appear to have been backported yet into https://github.com/pantheon-systems/pantheon-mu-plugin/blob/main/inc/pantheon-page-cache.php (at the [latest/current hash](https://github.com/pantheon-systems/pantheon-mu-plugin/blob/fdd3052f3e4a38b166668cc51739f2dec7d5ff98/inc/pantheon-page-cache.php)) as of this note/issue? 

So correct to file an issue, but in the wrong GitHub and the wrong issue! :) Need to backport the changes into the `pantheon-systems/pantheon-mu-plugin/` repo. :) 

## Plugin Stack
- Gutenberg Editor Enabled for Custom Post Type with Custom Taxonomy/Taxonomies
- ACF Pro
- Yoast SEO (and PRO, but errors for both with/without)
- Pantheon (mu-plugin)

(I listed ACF Pro because I know it has some integrations with Yoast SEO, but the problem does not occur when ACF Pro is active.  Its only with this specific combination of plugins.)

## Background
We upgraded our "stack" in January with the following changes:
1. Upgraded to WordPress 6.x, ACF Pro 6.x, and Yoast 19.1+ (moved to `20.1`, but tested `19.1` and above in case it was Yoast 20.x).
2. Upgraded from "Pantheon" `1.0.0` to the `mu-plugin` Composer-based version (including the recommended 'loader' file).
  - I did note a change in Aug '22 where the `term` caching was "deprecated" and to `use the CDN`. Unsure if related.

Once all updates were applied, we noticed an issue where the "Add New <Taxonomy>" button "appears" non-functional.  Appears is in quotes because the terms **will** (randomly) save to the custom taxonomy (though not actually be seen on the page).

**Note:** After initial cache clear, it sometimes "works right", but then will not for other pages and/or after a refresh.

## Testing
Occurs both on a "Pantheon" configured Lando environment and/or any given Pantheon environment, including LIVE.

1. Enable listed plugins.
2. Create the CPT and custom Taxonomy
3. Navigate to create/edit a page in FireFox (for the tools / next-steps).
4. Before making changes, open the inspector, navigate to the "Network" tab, and clear it.
5. Try to add a new term.
6. When it fails, note that `api-fetch-min.js` is pinged twice.  Both times the "returned" content is listed as `cached` under the Transferred tab.  (If not, give a refresh and/or edit a different page.)

## "Fixing" the issue
Any of these solutions seems to "fix" the issue, though clearly none of them are _valid_ solutions.

1. Disable Yoast SEO.
2. Remove the Pantheon mu-plugin and loader file(s) from the `mu-plugins/` folder.
3. Add the `define('WP_CACHE', FALSE);`
4. Check the `Disable Cache` checkbox on the "Network" tab of FireFox tools.
5. Using the Pantheon Adv. Page Cache plugin, set the TTL to `0`.

Running `wp cache flush` via the CLI also _sometimes_ fixes the issue for a single pageload.

## Example (Screenshot)

I attempted to add the term "Another Test".  You can see in the screenshot both that the "Transferred" items are `cached` and that the term "Another Test" is not present.

Please forgive creative term names. It kept working for a minute, then failing, due to code-changes. :D 

![image](https://user-images.githubusercontent.com/1015474/220709553-57a1ebef-3760-4098-a892-37a316e38acd.png)

Feel free to ping me via Pantheon Slack, if needed, to see two environments where this issue is occurring. 👍

**Comment by jazzsequence** [comment]
This issue was solved in the WordPress upstream but the fix was never carried over when we split the `mu-plugin` into its own repository.

See: https://github.com/pantheon-systems/WordPress/pull/337/files

**Comment by cleverington** [comment]
@jazzsequence 

I can confirm that https://github.com/pantheon-systems/pantheon-mu-plugin/releases/tag/1.0.4 appears to have fixed the issue and have successfully tested the fix both on Lando and Pantheon  (with and without the Adv Page Cache plugin).

**Comment by kporras07** [comment]
That's great to know. Thanks for confirming.

I'm going ahead and closing this issue. Please feel free to reopen (or open a new one) if something else arises

**Comment by jazzsequence** [comment]
@cleverington Thanks again for the report and for confirming!
